# .github/workflows/generate-diagram.yml
name: Generate Data Flow Diagram

on:
  push:
    branches:
      - main # mainブランチにpushされたら実行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を許可
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # --- 変更点: Node.jsとMermaid-CLIをインストール ---
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli

      - name: Install Python dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate diagram image and markdown
        run: python scripts/generate_flow.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate data flow diagram image"
          # --- 変更点: コミット対象にpuppeteer-config.jsonを追加 ---
          file_pattern: "architecture/02-data-flow.md architecture/data-flow-diagram.svg scripts/puppeteer-config.json"
