# .github/workflows/generate-diagram.yml
name: Generate Data Flow Diagram

on:
  push:
    branches:
      - main  # mainブランチにpushされたら実行

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # リポジトリへの書き込み権限を許可
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r scripts/requirements.txt

      - name: Generate diagram
        run: python scripts/generate_flow.py

      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: Auto-generate data flow diagram"
          file_pattern: "architecture/02_data-flow.md"